# Generated by Django 4.1.4 on 2023-02-01 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200907_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the dish.', max_length=70)),
                ('description', models.TextField(help_text='The Description text.')),
                ('receipe', models.TextField(help_text='The Receipe text.')),
                ('publication_date', models.DateField(verbose_name='Date the dish was published.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dish_photos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookcontributor',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookContributor',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(default=None, help_text='The Dish that this review is for.', on_delete=django.db.models.deletion.CASCADE, to='reviews.dish'),
        ),
    ]
